config/routes.rb
Kbs::Application.routes.draw do
  devise_for :emps

  root :to => 'home#index'
  resources :balances do
    collection do
      get :login, :q, :month_list, :ch, :serforch
    end
  end

  namespace :admin do
  	resources :companies, :agreements, :channels, :products, :balances
    resources :clients do
      member do
        get :add_user
      end
    end
    resources :user_infos, :users
    resources :emps
    resources :imports do
      collection do
        get :check_data, :save_data, :clear_data, :import_data
      end
    end
    match 'checkpro' => 'channels#checkpro'
    match 'mm_data' => 'reports#mm_data'
    match 'sjflot' => 'imports#sjfloat'
    match 'wap_read' => 'reports#wap_read'
    match 'data_tools(/:action)' => 'data_tools'
    match 'reports(/:action)' => 'reports'
    match 'diagrams(/:action)' => 'diagrams'
    match 'yz_caixin' => 'reports#yz_caixin'
    match 'zy_caixin' => 'reports#zy_caixin'
    match 'balabyclient/:id' => 'balances#balabyclient'
  end
  match '/admin', :to => 'admin/home#index', :as => :admin

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :channels
	has_many :balances
	has_many :agreements
	has_many :users
	has_many :user_infos
end

app/controllers/admin/clients_controller.rb
module Admin
  class ClientsController < ResourceController
    update.after :update_channels
    create.after :auto_add_user


  	def add_user
  		ui = UserInfo.new
  		ui.build_user
      ui.user.login_name = 'A' + params[:id]
      ui.client_id = params[:id].to_i
      ui.save
  	end
  	
  	def update_channels
	  	if params[:rm_channels]
		  	params[:rm_channels].each do |ch_id, b|
		  		ch = Channel.find(ch_id)
		  		@object.channels.delete(ch) if @object.channels.include?(ch)
		  	end
	  	end
	  	if params[:add_channels]
	  		params[:add_channels].each do |ch_id, b|
	  			ch = Channel.find(ch_id)
	  			@object.channels << ch unless @object.channels.include?(ch)
	  		end
	  	end
  	end

    def auto_add_user
      ui = UserInfo.new
      ui.build_user
      ui.user.login_name = 'A' + @object.id.to_s
      @object.user_infos << ui
      ui.save
    end

  end
end

app/views/admin/clients/_form.html.erb
<%= form_for([:admin, @object], :remote => true) do |f| %>
<div class='container'>
  <div class='span-8'>
  <div class="field">
    <%= f.label '客户名称' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label '联系电话' %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label '备注' %><br />
    <%= f.text_field :remark %>
  </div>
<fieldset><legend>账户信息</legend>
  <div class="field">
    <%= f.label '账户余额' %>:
    <%= @object.balance %>
  </div>
  <div class="field">
    <%= f.label '上次登录' %>:
    <%= @object.last_login %>
  </div>

   <div class="field">
    <%= f.label '结算日期' %>:
    <%= @object.balance_date %>
  </div>
   <div class="field">
    <%= f.label '上次支付' %>:
    <%= @object.last_pay_date %>
  </div>
</fieldset>
  <%= link_to '{新增登录}', admin_client_path(@object)+ '/add_user', :remote => true if @object.id  %>

<fieldset><legend>登录账户</legend>
  <% @object.user_infos.each do |ui| %>
  <%= link_to "#{ui.id}:#{ui.user.login_name if ui.user}", edit_admin_user_info_path(ui), :remote => true %>
  <% end %>
</fieldset>
  </div>

  <div class='span-8 last'>
    <% if params[:id] %>
	<fieldset><legend>已绑定渠道</legend>
    <% Channel.find_all_by_client_id(params[:id]).each do |ch|%>
    <div>
    <input type="checkbox" name="rm_channels[<%= ch.id %>]" id="<%= dom_id ch %>" />
    <label for="<%= dom_id ch %>"><%= ch.channel_number %></label>
  </div>
    <% end %>
	</fieldset>
	<fieldset><legend>空闲渠道</legend>
    <% Channel.where('client_id is null or client_id=0').each do |ch| %>
    <div>
    <input type="checkbox" name="add_channels[<%= ch.id %>]" id="<%= dom_id ch%>" />
    <label for="<%= dom_id ch %>"><%= ch.channel_number %></label>
    </div>
    <% end %>
	</fieldset>
    <% end %>   
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/clients/_row.html.erb
  <tr id='<%= dom_id obj %>'>
    <td><%= obj.id %></td>
    <td> <a href="balabyclient/<%= obj.id %>"><%= obj.name %></a></td>
    <td><%= obj.tel %></td>
    <td><%= obj.remark %></td>
    <td><%= obj.balance %></td>
    <td><%= l obj.last_login, :format => :long if obj.last_login %></td>
    <td><%= l obj.balance_date, :format => :short if obj.balance_date %></td>
    <td><%= l obj.last_pay_date, :format => :short if obj.last_pay_date %><td>
    <td><%= l obj.updated_at, :format => :long %></td>
    <td><%= link_to '编辑', edit_admin_client_path(obj), :remote => true %></td>
    <td><%= link_to '删除', admin_client_path(obj), :confirm => '确定要删除?', :method => :delete, :remote => true %></td>
  </tr>

app/views/admin/clients/add_user.js.erb
alert("新增登录用户成功");
$('.dialog-window').dialog('close');

app/views/admin/clients/index.html.erb
<h2>客户列表</h2>
<div class='toolbar'>
  <ul class='actions'>
    <li>

  <%= form_for [:admin, @search] do |f| %>
  姓名: <%= f.text_field :name_contains %>
  <%= f.submit '查找' %>
  <% end %>

    </li>
    <li><%= link_to_with_icon 'add', '新建客户', new_admin_client_path, :remote => true %>
</li>
</ul>
</div>
<%= will_paginate(@collection) %>
<table class='data-list'>
  <thead>
  <tr>
    <th>客户编号</th>
    <th>姓名</th>
    <th>电话</th>
    <th>备注</th>
    <th>结算数据</th>
    <th>最后登陆</th>
    <th>数据结算日期</th>
    <th>最后付款日期</th>
    <th>修改时间</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @collection.each do |client| %>
   <%= render :partial =>'row', :locals => {:obj => client} %>
  <% end %>
</tbody>
</table>
<%= will_paginate(@collection) %>

<div class='dialog-window'></div>
<br />