config/routes.rb
Kbs::Application.routes.draw do
  devise_for :emps

  root :to => 'home#index'
  resources :balances do
    collection do
      get :login, :q, :month_list, :ch, :serforch
    end
  end

  namespace :admin do
  	resources :companies, :agreements, :channels, :products, :balances
    resources :clients do
      member do
        get :add_user
      end
    end
    resources :user_infos, :users
    resources :emps
    resources :imports do
      collection do
        get :check_data, :save_data, :clear_data, :import_data
      end
    end
    match 'checkpro' => 'channels#checkpro'
    match 'mm_data' => 'reports#mm_data'
    match 'sjflot' => 'imports#sjfloat'
    match 'wap_read' => 'reports#wap_read'
    match 'data_tools(/:action)' => 'data_tools'
    match 'reports(/:action)' => 'reports'
    match 'diagrams(/:action)' => 'diagrams'
    match 'yz_caixin' => 'reports#yz_caixin'
    match 'zy_caixin' => 'reports#zy_caixin'
    match 'balabyclient/:id' => 'balances#balabyclient'
  end
  match '/admin', :to => 'admin/home#index', :as => :admin

end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :client
  belongs_to :user
end

app/controllers/admin/user_infos_controller.rb
module Admin
  class UserInfosController < ResourceController
  	def seachuser
  		@u = User.all
  	end
  end
end

app/views/admin/user_infos/_form.html.erb
<div class='container'>
  <div class='span-8'>
<%= form_for([:admin, @object], :remote => true) do |f| %>
  <div class="field">
    <%= f.label '真实姓名' %><br />
    <%= f.text_field :real_name %>
  </div>
  <div class="field">
    <%= f.label '联系电话' %><br />
    <%= f.text_field :phone %>
  </div>
   <div class="field">
    <%= f.label '网站' %><br />
    <%= f.text_field :website %>
  </div>

  <br />
  <div class="actions">
    <%= f.submit '保存' %>
  </div>
<% end %>
  </div>
  <div class='span-8 last'>
<%
unless @object.user
  @object.build_user
  @object.user.login_name = 'AU' + @object.id.to_s 
  @object.save
end
u = @object.user %>
<fieldset>
  <legend>用户登录信息</legend>
  <p>登录名: <%= u.login_name %></p>
  <p>Email: <%= u.email %></p>
  <p>(修改用户登录密码)</p>
<%= link_to '修改用户登录信息', edit_admin_user_path(u), :remote => true %>

</fieldset>
  </div>
</div>

app/views/admin/user_infos/_row.html.erb
  <% u = obj.user %>
  <tr id='<%= dom_id obj %>'>
  	<td><%= obj.id %></td>
    <td><%= u.login_name if u %></td>
    <td><%= obj.client.name if obj.client %>
    <td><%= u.email if u %></td>
    <td><%= obj.real_name %></td>
    <td><%= obj.phone %></td>
    <td><%= obj.website %></td>
    <td><%= u.sign_in_count if u %></td>
    <td><%= l u.current_sign_in_at, :format => :long if u && u.current_sign_in_at %></td>
    <td><%= l u.last_sign_in_at, :format => :long if u && u.last_sign_in_at %></td>
    <td><%= u.current_sign_in_ip if u %></td>
    <td><%= u.last_sign_in_ip if u %></td>
    <td><%= link_to '编辑', edit_admin_user_info_path(obj), :remote => true %> | 
    <%= link_to '删除', admin_user_info_path(obj), :confirm => '确定删除？', :method => :delete, :remote => true %></td>
  </tr>

app/views/admin/user_infos/index.html.erb
<h2>用户列表</h2>

<div class='toolbar'>
  <ul class='actions'>
    <li>
  <%= form_for [:admin, @search] do |f| %>
  登录名: <%= f.text_field :user_login_name_contains %>
  <%= f.submit '查找' %>
  <% end %>
    </li>

    <li>
  <%= link_to_with_icon 'add', '新建用户', new_admin_user_path, :remote => true %>
</li>
</ul>
</div>
<%= will_paginate(@collection) %>
<table class='data-list'>
  <thead>
  <tr>
    <th>用户编号</th>
    <th>登录名称</th>
    <th>所属客户</th>
    <th>真实姓名</th>
    <th>联系电话</th>
    <th>网站</th>
    <th>邮箱</th>
    <th>公司</th>
    <th>登录次数</th>
    <th>当前登录时间</th>
    <th>最后登录时间</th>
    <th>当前登录IP</th>
    <th>最后登录IP</th>
    <th>&nbsp;</th>
  </tr>
</thead>
<tbody>
  <% @collection.each do |client| %>
   <%= render :partial =>'row', :locals => {:obj => client} %>
  <% end %>
</tbody>
</table>
<%= will_paginate(@collection) %>

<div class='dialog-window'></div>
<br />