config/routes.rb
Kbs::Application.routes.draw do
  devise_for :emps

  root :to => 'home#index'
  resources :balances do
    collection do
      get :login, :q, :month_list, :ch, :serforch
    end
  end

  namespace :admin do
  	resources :companies, :agreements, :channels, :products, :balances
    resources :clients do
      member do
        get :add_user
      end
    end
    resources :user_infos, :users
    resources :emps
    resources :imports do
      collection do
        get :check_data, :save_data, :clear_data, :import_data
      end
    end
    match 'checkpro' => 'channels#checkpro'
    match 'mm_data' => 'reports#mm_data'
    match 'sjflot' => 'imports#sjfloat'
    match 'wap_read' => 'reports#wap_read'
    match 'data_tools(/:action)' => 'data_tools'
    match 'reports(/:action)' => 'reports'
    match 'diagrams(/:action)' => 'diagrams'
    match 'yz_caixin' => 'reports#yz_caixin'
    match 'zy_caixin' => 'reports#zy_caixin'
    match 'balabyclient/:id' => 'balances#balabyclient'
  end
  match '/admin', :to => 'admin/home#index', :as => :admin

end

app/models/emp.rb
class Emp < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :encryptable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login_name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/emps_controller.rb
module Admin
  class EmpsController < ResourceController
  end
end

app/views/admin/emps/_form.html.erb
<%= form_for([:admin, @object], :remote => true) do |f| %>
<div class='container'>
  <div class='span-8'>
  <div class="field">
    <%= f.label '登录名' %><br />
    <%= f.text_field :login_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label '登录密码' %><br />
    <%= f.text_field :password %>
  </div>
 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/emps/_row.html.erb
  <tr id='<%= dom_id obj %>'>
  	<td><%= obj.id %></td>
    <td><%= obj.login_name %></td>
     <td><%= obj.email %></td>
    <td><%= obj.sign_in_count %></td>
    <td><%= l obj.current_sign_in_at, :format => :long if obj.current_sign_in_at %></td>
    <td><%= l obj.last_sign_in_at, :format => :long if obj.last_sign_in_at %></td>
    <td><%= obj.current_sign_in_ip %></td>
    <td><%= obj.last_sign_in_ip %></td>
    <td><%= link_to '编辑', edit_admin_emp_path(obj), :remote => true %> |
    <%= link_to '删除', admin_emp_path(obj), :confirm => '确定删除？', :method => :delete, :remote => true %></td>
  </tr>

app/views/admin/emps/index.html.erb
<h2>管理员列表</h2>
<div class='toolbar'>
  <ul class='actions'>
    <li><%= link_to_with_icon 'add', '新建管理员', new_admin_emp_path, :remote => true %></li>
  </ul>
</div>
<%= will_paginate(@collection) %>
<table class='data-list'>
  <thead>
  <tr>
    <th>用户编号</th>
    <th>登录名称</th>
    <th>邮箱</th>
    <th>登录次数</th>
    <th>当前登录时间</th>
    <th>最后登录时间</th>
    <th>当前登录IP</th>
    <th>最后登录IP</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @collection.each do |emp| %>
   <%= render :partial =>'row', :locals => {:obj => emp} %>
  <% end %>
</tbody>
</table>
<%= will_paginate(@collection) %>

<div class='dialog-window'></div>
<br />