config/routes.rb
Kbs::Application.routes.draw do
  devise_for :emps

  root :to => 'home#index'
  resources :balances do
    collection do
      get :login, :q, :month_list, :ch, :serforch
    end
  end

  namespace :admin do
  	resources :companies, :agreements, :channels, :products, :balances
    resources :clients do
      member do
        get :add_user
      end
    end
    resources :user_infos, :users
    resources :emps
    resources :imports do
      collection do
        get :check_data, :save_data, :clear_data, :import_data
      end
    end
    match 'checkpro' => 'channels#checkpro'
    match 'mm_data' => 'reports#mm_data'
    match 'sjflot' => 'imports#sjfloat'
    match 'wap_read' => 'reports#wap_read'
    match 'data_tools(/:action)' => 'data_tools'
    match 'reports(/:action)' => 'reports'
    match 'diagrams(/:action)' => 'diagrams'
    match 'yz_caixin' => 'reports#yz_caixin'
    match 'zy_caixin' => 'reports#zy_caixin'
    match 'balabyclient/:id' => 'balances#balabyclient'
  end
  match '/admin', :to => 'admin/home#index', :as => :admin

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :channels
	has_many :agreements
	has_many :balances

	default_scope :order => 'channel_number'
end

app/controllers/admin/products_controller.rb
module Admin
class ProductsController < ResourceController
  
end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @object], :remote => true) do |f| %>
  <div class="field">
    <%= f.label '产品名称' %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label '产品说明' %><br />
    <%= f.text_field :description %>
  </div>
   <div class="field">
    <%= f.label '渠道号' %><br />
    <%= f.text_field :channel_number %>
  </div>
   <div class="field">
    <%= f.label '产品价格' %><br />
    <%= f.text_field :price %>
  </div>
    <div class="field">
    <%= f.label '有效状态' %>: 
   <%= f.radio_button :status, '0' %>
   <%= f.label 'status_0', '关闭' %>
   <%= f.radio_button :status, '1' %>
   <%= f.label 'status_1', '有效' %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/_row.html.erb
  <tr id='<%= dom_id obj %>'>
    <td><%= link_to obj.channel_number, admin_channels_path + "?search[channel_number_starts_with]=#{obj.channel_number}" %></td>
    <td><%= obj.title %> (<%= obj.channels.count %>)</td>
    <td><%= obj.description %></td>
    <td><%= obj.price %></td>
    <td><%= obj.status %></td>
    <td><%= l obj.updated_at, :format => :long %></td>
    <td>
    	<%= link_to '编辑', edit_admin_product_path(obj), :remote => true %> |
    	<%= link_to '删除', admin_product_path(obj), :confirm => '确定删除？', :method => :delete, :remote => true %></td>
  </tr>

app/views/admin/products/index.html.erb
<% content_for :breadcrumbs do %>
  <ul>
    <li><a href="/admin">Home</a></li>
    <li>&raquo;</li>
    <li>数据维护</li>
    <li>&raquo;</li>
    <li>产品渠道</li>
    <li>&raquo;</li>
    <li>产品列表</li>
  </ul>
<% end %>

<h2>产品列表</h2>
<div class='toolbar'>
  <ul class='actions'>
  <li>
      <%= form_for [:admin, @search] do |f| %>
      登录名: <%= f.text_field :title_contains %>
      <%= f.submit '查找' %>
      <% end %>
    </li>

    <li><%= link_to_with_icon 'add', '新建产品', new_admin_product_path, :remote => true %></li>
  </ul>
</div>
<%= will_paginate(@collection) %>

<table class='data-list'>
  <thead>
  <tr>
    <th>渠道号</th>
    <th>产品名称</th>
    <th>描述</th>
    <th>产品价</th>
    <th>状态</th>
    <th>更改时间</th>
    <th></th>
  </tr>
</thead>
<tbody>
  <% @collection.each do |product| %>
   <%= render :partial =>'row', :locals => {:obj => product} %>
  <% end %>
</tbody>
</table>
<%= will_paginate(@collection) %>

<div class='dialog-window'></div>
<br />